### PR TITLE
Add json xml format arguments

### PR DESCRIPTION
**Pull request by seisokeii**
At the NYCU CSIT, we tested this function with approximately fifty switches, and it worked fine, fast, and as expected.
However, we cannot be sure if the function will perform as expected in a large-scale data center.

### CODE REVIEW

**Comment by seisokeii** [comment]
A more detailed description of this change: 
When developing Jinja2 templates, we want to ensure the templates remain readable even after adding Jinja2 syntax, as shown below. 
Use Cisco Nexus feature RESTCONF for example:
```jinja2
{% if 'Feature' in host.facts %}
    {% set features = host.facts.Feature %}
    <fm-items>
        <ssh-items>
            <adminSt>enabled</adminSt>
        </ssh-items>
        <ntpd-items>
            <adminSt>enabled</adminSt>
        </ntpd-items>
        {% for feature in features %}
            {% for key, value in feature.items() %}
                <{{ value | rep }}-items>
                    <adminSt>enabled</adminSt>
                </{{ value | rep }}-items>
            {% endfor %}
        {% endfor %}
    </fm-items>
{% endif %}
```
If we don't format this XML after render we will see a lot of extra whitespaces when debugging, as seen below
```text

        <fm-items>
        <ssh-items>
            <adminSt>enabled</adminSt>
        </ssh-items>
        <ntpd-items>
            <adminSt>enabled</adminSt>
        </ntpd-items>
                                    <nxapi-items>
                    <adminSt>enabled</adminSt>
                </nxapi-items>
                                                <bashshell-items>
                    <adminSt>enabled</adminSt>
blabla...
```

**Comment by dbarrosop** [comment]
Hi, thanks for the PR. I am not sure what others may think but I am a bit on the fence about this functionality. I feel this functionality really doesn't belong here, that it'd be better off implemented outside of this library (i.e. as a grouped task). Either that or passing a user-defined "format" function. I.e.:

```python
def template_file(
    task: Task,
    template: str,
    path: str,
    jinja_filters: Optional[FiltersDict] = None,
    jinja_env: Optional[Environment] = None,
    formatFunc: Callable[[str], str] = None,
    **kwargs: Any
):
...
    if formatFunc is not None:
          text = formatFunc(text)
    return Result(host=task.host, result=text)
```

Otherwise this isn't going to scale either as others may want to format yaml, toml, or any other type.

Thanks again, let's see first what other think before deciding how to move forward.

**Comment by seisokeii** [comment]
Fine. Thanks for your suggestion.

**Comment by seisokeii** [comment]
I think `formatFunc` argument is good and clean. And I've update the code as suggestion and also write usage and example code in README.

BUT I don't know how to use git to push on this PR because I delete this commit...

Another problem is I don't know how to write guidance into docs, so I need someone to help me to update this.

Feel free to copy and modify my commit code and contribute to official. That's all I can do for now QQ

My commit URL: [https://github.com/seisokeii/nornir_jinja2/commits/master/](https://github.com/seisokeii/nornir_jinja2/commits/master/)

**Pull request closed without merging**
